[default]
ident = "mediator"
key_seed = "4bo9pLUEahsPqerR756HCQ4A9m3fS7WKwUsXru7CSDFd"
did = "did:key:z6MkpFZ86WuUpihn1mTRbpBCGE6YpCvsBYtZQYnd9jcuAUup"

[debug]
port = 8000
ext_hostname = "http://localhost:8000"
ext_service = "http://localhost:8001"

[release]
address = "0.0.0.0"
port = 8080
ext_hostname = "https://mediator.ssi.quest"
ext_service = "https://mediator.ssi.quest"