[default]
ident = "mediator"
key_seed = "293WPZ2PJQmNFN3MCMu49RM6ukVEQkfM1aJp9gJ8JhAs"
did_key = "did:key:z6LSp5C8TjVvzJx3Kh5MFcdkHit6CVKTQ9RmTr3jLyE77BfH"
did_iota = "did:iota:11PwbeZDPtksuh5rTojk7eALu7R7adYQkBakt49tQE7"
wallet_path = "wallet.hold.example"
wallet_password = "changeme"

[debug]
port = 8000
ext_hostname = "http://localhost:8000"
ext_service = "http://localhost:8000"

[release]
address = "0.0.0.0"
port = 8080
ext_hostname = "https://mediator.ssi.quest"
ext_service = "https://mediator.ssi.quest"