[default]
ident = "mediator"
key_seed = "F3JbRaYFNWwpvxSZHVV7i5pcpdTjGWiJHRCbUVHe9wWu"
did_key = "did:key:z6LSopzj1Rwdjx7RAUaRYwDPSzwXudhjE2PU7iimBzcHUqEi"
did_iota = "did:iota:Dtt6G44R8pMSGLRRZPnzsCatHftxqSLwpNwfoiivvAxH"
wallet_path = "wallet.hold.example"
wallet_password = "changeme"

[debug]
port = 8000
ext_hostname = "http://localhost:8000"
ext_service = "http://localhost:8000"

[release]
address = "0.0.0.0"
port = 8080
ext_hostname = "https://mediator.ssi.quest"
ext_service = "https://mediator.ssi.quest"