[default]
ident = "mediator"
key_seed = "4bo9pLUEahsPqerR756HCQ4A9m3fS7WKwUsXru7CSDFd"
did_key = "did:key:z6MkpFZ86WuUpihn1mTRbpBCGE6YpCvsBYtZQYnd9jcuAUup"
did_iota = "did:iota:6dgiVE6EhCFqEEBDk6CedUq8aeeqQwQeAVSbZz8PgMzi"
wallet_path = "wallet.hold.example"
wallet_password = "changeme"

[debug]
port = 8000
ext_hostname = "http://localhost:8000"
ext_service = "http://localhost:8000"

[release]
address = "0.0.0.0"
port = 8080
ext_hostname = "https://mediator.ssi.quest"
ext_service = "https://mediator.ssi.quest"